# Generated by Django 5.2.3 on 2025-06-29 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productvariation_size_productvariation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_types', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.productvariationtype')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
