# Generated by Django 5.2.3 on 2025-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productvariationtype_productvariationvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariationvalue',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga khusus untuk value ini (opsional)', max_digits=10, null=True),
        ),
    ]
