# Generated by Django 5.2.3 on 2025-07-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method'),
        ('store', '0011_order_shipping_cost'),
    ]

    operations = [
    ]
