# Generated by Django 5.2.3 on 2025-07-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_merge_20250704_0505'),
        ('store', '0012_orderitem_size'),
    ]

    operations = [
    ]
